# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accordance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliernumber',
            name='accNumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accordance.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliernumber',
            name='supNumber',
            field=models.CharField(max_length=15),
        ),
    ]
