# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordance', '0002_auto_20170418_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supplierNumber',
            new_name='SupplierCode',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='suppliercode',
            old_name='accNumber',
            new_name='acc_code',
        ),
        migrations.RenameField(
            model_name='suppliercode',
            old_name='supNumber',
            new_name='sup_code',
        ),
    ]
