# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordance', '0003_auto_20170418_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='base_code',
        ),
    ]
