# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accordance', '0005_auto_20170418_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='match',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
