# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20170419_1649'),
        ('accordance', '0006_auto_20170419_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accordance.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accordance.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together=set([('product', 'warehouse')]),
        ),
    ]
