# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accordance', '0007_auto_20170419_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='supplier.Warehouse'),
        ),
    ]
