# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set([('city', 'supplier')]),
        ),
        migrations.AddField(
            model_name='quantity',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together=set([('product', 'warehouse')]),
        ),
    ]
