# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordance', '0007_auto_20170419_1659'),
        ('supplier', '0002_auto_20170419_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
