# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20170421_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
