# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancy_rsqm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='aaa',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
